---
apiVersion: v1
kind: Pod
metadata:
  name: daguploader
spec:
  serviceAccountName: airflow-worker

  containers:
    - name: base
      command: ["python", "-c"]
      args: ["import time;time.sleep(300);print('hello world');"]
      image: "harbor.infra.wish-cn.com/wish/wishpost-airflow@sha256:089400dea49a5f7935fd42e240483ccb2f722c4fd48d6f41a8c566280d725ba4"
      imagePullPolicy: Always
      ports: []
         
      env:
        - name: PG_HOST
          value: "wishpost-rds-snapshot.bjs.i.wish.com"
        - name: PG_USERNAME
          value: "wishpost"
        - name: PG_PASSWORD
          value: "wishpost"
        - name: PG_DATABASE
          value: "prod"
        
  restartPolicy: Never