---
apiVersion: v1
kind: Pod
metadata:
  name: daguploader
spec:
  initContainers:
    - name: init-container
      image: "python:3.6"
      command: ["python", "-c"]
      args: ["print('hello world')"]
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi

  containers:
    - name: base
      command: ["python", "-c"]
      args: ["print('hello world')"]
      image: "python:3.6"
      imagePullPolicy: IfNotPresent
      ports: []
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi
      # volumeMounts:
      #   - name: shared-volume
      #     mountPath: "/tmp/mnt"
  #hostNetwork: false
  restartPolicy: Never
  # volumes:
  # - name: shared-volume
  #   emptyDir: {}